### ISSUE TITLE
Explain permissions 

### ISSUE THREAD

**Issue by stefanbuck** [rgehan/octolenses-browser-extension#29]
**Is your feature request related to a problem? Please describe.**
By default, I'm suspicious when it comes to permissions that an app or extensions requires. For me it's really important to understand why an extension needs those permissions. In your case the `Read your browser history` permission needs some clarity why this is needed. 

**Describe the solution you'd like**
Try to remove them or narrow them down as much as possible. E.g. `"https://github.com/*",` instead of  `*://*.github.com/*`

**Describe alternatives you've considered**
Explain why your extensions needs all those permissions.

**Additional context**
<img width="441" alt="screen shot 2018-08-18 at 20 16 20" src="https://user-images.githubusercontent.com/1393946/44302153-94c63280-a323-11e8-8c11-01d28a7d1b4a.png">

**Comment by rgehan** [comment]
You should be suspicious, that's a good thing.

In this case, these are permissions I used to think were necessary, but that aren't anymore. I'll remove them with the next release
