### ISSUE TITLE
Show PR status in list

### ISSUE THREAD

**Issue by pendletons** [rgehan/octolenses-browser-extension#37]
**Is your feature request related to a problem? Please describe.**

It's unclear what PRs in the list need action based on their review status, because this info isn't displayed in the list anywhere.

**Describe the solution you'd like**

It would be really helpful to see some sort of status on the PR list (awaiting review, approved, etc.) so that you know what status a PR has.

**Describe alternatives you've considered**

I've created a workaround by adding additional lists with review status filters, which works but clutters up the dashboard.

**Comment by rgehan** [comment]
We could use the following symbols:
- Orange dot for "awaiting review"
- Red cross for "changes requested"
- Green tick for "changes approved"

Would that fulfill your needs?

**Comment by rgehan** [comment]
I've done a few tests, and it looks feasible. The only problem is that it would require adding an additional request for each PR, which would very quickly rate-limit the users.

I think we could mitigate this by using the GraphQL API (V4), but that would imply big changes to the extension.

I think the GraphQL query would then look like this:
```graphql
fragment _PR on PullRequest {
  title
  url
  repository {
    nameWithOwner
  }
  comments {
    totalCount
  }
  reviews(first: 100) {
    nodes {
      createdAt
			author { login }
      state
    }
  }
}

fragment _Issue on Issue {
  title
  url
  repository {
    nameWithOwner
  }
  comments {
    totalCount
  }
}

{
  search(
		query: "is:open type:pr repo:rgehan/octolenses-browser-extension", 
		type: ISSUE,
		first: 100
	) {
    edges {
      node {
        ... on PullRequest {
          ..._PR
        }
        ... on Issue {
          ..._Issue
        }
      }
    }
  }
}
```

The GitHub API returns, for each PR, an array of reviews like this one:
```js
const reviews = [
  {
    createdAt: "2018-09-01T13:48:06Z",
    author: {
      login: "rgehan",
    },
    state: "DISMISSED",
  },
  {
    createdAt: "2018-09-01T13:48:39Z",
    author: {
      login: "rgehan2",
    },
    state: "CHANGES_REQUESTED",
  },
  {
    createdAt: "2018-09-01T13:49:22Z",
    author: {
      login: "rgehan"
    },
    state: "CHANGES_REQUESTED"
  },
  {
    createdAt: "2018-09-01T13:49:30Z",
    author: {
      login: "rgehan"
    },
    state: "APPROVED"
  }
];

// To determine the state of a PR, we'd just need to find the last
// status for each reviewer.
// =>

const statuses =_.chain(reviews)
  .keyBy('author.login')
  .map('state')
  .value();

// => ['APPROVED', 'CHANGES_REQUESTED']

const isFailed = statuses.includes('CHANGES_REQUESTED');
```

**Comment by rgehan** [comment]
I think the query should be something like this:
```gql
{
  search(query: "repo:laravel/framework is:open is:pr", type: ISSUE, first: 20) {
    edges {
      node {
        __typename
        ... on PullRequest {
          commits(last: 1) {
            edges {
              node {
                commit {
                  status {
                    state
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
