### ISSUE TITLE
Support Github Enterprise

### ISSUE THREAD

**Issue by jmcs** [rgehan/octolenses-browser-extension#47]
**Is your feature request related to a problem? Please describe.**
I use both github.com and Github Enterprise daily. Octolense only works with github.com.

**Describe the solution you'd like**
Octolense should also support Github Enterprise instances.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rgehan** [comment]
Hi, I'm unfortunately not familiar at all with Github Enterprise.

PRs are welcome if you're up for it! :)

**Comment by rgehan** [comment]
Generalized the issue in #50
